a = input('Digite Qualquer coisa: ')
print('O Tipo primitivo dessa coisa é', type(a))
print('Só tem espaços ?', a.isspace())
print('É numerico ?', a.isnumeric())
print('É Alfabético ?', a.isalpha())
print('É Alfanumérico ?', a.isalnum())
print('É decimal ?', a.isdecimal())
print('É Maiusculo ?', a.isupper())
print('É Minusculo ?', a.islower())
print('É Impresso ?', a.isprintable())
print('É Maiusculo e Minusculo ?', a.istitle())